version: '3.5'

services:
  db:
    container_name: marketsi_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Qwerty1234"
      POSTGRES_DB: "marketsi"
    ports: 
      - "5437:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: marketsi_storage
    driver: bridge